name = "kirby-copilot-website"
main = "./.output/server/index.mjs"
workers_dev = false
compatibility_date = "2023-06-13"

rules = [
  { type = "ESModule", globs = ["**/*.js", "**/*.mjs"]},
]

[site]
bucket = ".output/public"
